name: Cypress Tests

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action on
  pull_request:
    branches:
      - main  # Change this to the branch you want to trigger the action on

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version you're using

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend  # Adjust if necessary

      - name: Start application
        run: npm start &
        working-directory: ./frontend  # Adjust if necessary

      - name: Wait for application to be ready
        run: npx wait-on http://localhost:3000  # Adjust if necessary

      - name: Run Cypress tests
        run: npx cypress run
        working-directory: ./frontend  # Adjust if necessary

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: ./frontend/cypress/results  # Adjust if necessary
